_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: localhost
smtp_hostbackup: ''
smtp_port: '1025'
smtp_protocol: standard
smtp_autotls: false
smtp_timeout: 30
smtp_username: magnuscarlesn097@gmail.com
smtp_password: iyxbajujsnmapgaj
smtp_from: ''
smtp_fromname: 'Indranil roy'
smtp_client_hostname: smtp.gmail.com
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: indranil.roy@innoraft.com
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
