_core:
  default_config_hash: 8_qX6deS-sD3xX39HCLpemQQ6C7YuiKujIdB3qH7cZI
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: 'https://www.instagram.com/google'
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: 'https://www.youtube.com/user/Google'
vimeo_url: 'https://vimeo.com/'
telegram_url: 'https://telegram.org/'
whatsapp_url: 'https://web.whatsapp.com/'
github_url: 'https://github.com/'
vk_url: ''
slider_show: 1
slider_code: "<li>\r\n  <h1>Hey  I am <em>Indranil Roy</em> </h1>\r\n  <p>This is a portfolio website</p>\r\n  <a class=\"button-link\" href=\"#\">Get Started</a>\r\n</li>\r\n"
slider_image: {  }
slider_image_path: ''
front_sidebar: 0
google_font: local
bootstrapicons: 1
comment_user_pic: 1
node_author_pic: 0
node_tags: 0
font_icon_fontawesome: 1
font_icon_material: 1
copyright_text: 1
scrolltotop_on: 1
styling: 0
styling_code: ''
font_icon_fontawesome5: 0
font_icon_fontawesome6: 0
